apiVersion: v1
kind: Service
metadata:
  name: spark-service
  labels:
    app: spark-app
spec:
  ports:
    - name: metrics
      port: 4040
      targetPort: 4040
      protocol: TCP
  selector:
    app: spark-app