apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-app
  template:
    metadata:
      labels:
        app: spark-app
    spec:
      containers:
        - name: spark-app
          image: pairate/spark-app:0.0.1
          imagePullPolicy: Always
          command:
            - "/bin/bash"
            - "-c"
          args:
            - |
              /opt/spark/bin/spark-submit \
                --master k8s://https://192.168.49.2:8443 \
                --deploy-mode cluster \
                --class org.example.Main \
                --conf spark.kubernetes.file.upload.path="hdfs://hadoop-hadoop-hdfs-nn.default.svc:9000/spark" \
                --conf spark.kubernetes.driver.label.monitored-by=prometheus \
                --conf spark.ui.prometheus.enabled=true \
                --conf spark.executor.processTreeMetrics.enabled=true \
                --conf spark.kubernetes.driver.annotation.prometheus.io/scrape=true \
                --conf spark.kubernetes.driver.annotation.prometheus.io/path=/metrics/executors/prometheus/ \
                --conf spark.kubernetes.driver.annotation.prometheus.io/port=4040 \
                --conf spark.dynamicAllocation.enabled=false \
                --conf spark.executor.instances=2 \
                --conf spark.kubernetes.container.image=pairate/spark-app:0.0.1 \
                --conf spark.kafka.bootstrap.servers=my-cluster-kafka-bootstrap.default.svc:9092 \
                --conf spark.metrics.conf="/opt/spark/metrics.properties" \
                /opt/spark/work-dir/SparkStructured-1.0-SNAPSHOT.jar
